from django.urls import path
from main import views

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('login_submit/', views.login_submit, name="login_submit"),
    path('student<int:hostelid>/', views.student_homepage, name="student_homepage"),
    path('register/', views.register, name="register"),
    path('register_submit/', views.register_submit, name="register_submit"),
    path('home<int:studentid>/', views.home, name="home"),
    path('studyspace<int:studentid>/', views.view_studyspace, name="studyspace"),
    path('hostel<int:hostelid>/', views.view_hostel, name="view_hostel"),
    path('hostelloginsubmit<int:hostelid>/', views.hostelloginsubmit, name="hostelloginsubmit"),
    path('mathgroup/', views.mathgroup, name="mathgroup"),
    path('physicsgroup/', views.physicsgroup, name="physicsgroup"),
    path('biologygroup/', views.biologygroup, name="biologygroup"),
    path('computergroup/', views.computergroup, name="computergroup"),
    path('discussion<int:userid>/', views.discussion, name="discussion"),
    path('creatediscussion<int:userid>/', views.create_discussion, name="creatediscussion"),
    path('postdiscussion<int:userid>/', views.post_discussion, name="postdiscussion"),
    path('addresource<int:userid>/', views.addresource, name="addresource"),
    path('maintainance<int:hostelid>/', views.maintainance, name="maintainance"),
    path('dashboard<int:hostelid>/', views.dashboard, name="dashboard"),
    path('complaint<int:hostelid>/', views.complaint, name="complaint"),
    path('complaintsubmit<int:hostelid>/', views.submit_complaint, name="submit_complaint"),
    path('reedem<int:studentid>/', views.reedem, name="redeem"),
    path('redeemsubmit<int:studentid>/', views.redeem_submit, name="redeemsubmit"),
    path('math/', views.math, name="math"),
    path('physics/', views.physics, name="physics"),
    path('computer/', views.computer, name="computer"),
    path('biology/', views.biology, name="biology"),
    path('correctoptionclicked<int:studentid>/', views.correctoptionclicked, name="correctoptionclicked"),
]