# Generated by Django 5.1.5 on 2025-02-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hostel_student_email_student_interests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='interests',
            new_name='interest',
        ),
    ]
