# Generated by Django 5.1.5 on 2025-02-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_interests_student_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.CharField(blank=True, null=True),
        ),
    ]
