# Generated by Django 5.1.5 on 2025-02-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_warden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('content', models.TextField()),
                ('userid', models.TextField()),
            ],
        ),
    ]
