# Generated by Django 5.1.5 on 2025-02-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_discussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='userid',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='topic',
            field=models.CharField(max_length=150),
        ),
    ]
