# Generated by Django 5.1.5 on 2025-02-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_userid_discussion_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='credit_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
