# Generated by Django 5.1.5 on 2025-02-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_student_credit_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('resourceurl', models.CharField(max_length=1000)),
            ],
        ),
    ]
