# Generated by Django 5.1.5 on 2025-02-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='username',
            field=models.CharField(default='hello', max_length=300),
            preserve_default=False,
        ),
    ]
