# Generated by Django 5.1.5 on 2025-02-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_resource_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(default='Buddhanagar', max_length=100),
            preserve_default=False,
        ),
    ]
