# Generated by Django 5.1.5 on 2025-02-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_student_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='location',
            field=models.CharField(default='Buddhanagar', max_length=300),
            preserve_default=False,
        ),
    ]
