# Generated by Django 5.1.5 on 2025-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='hostelid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
