# Generated by Django 5.1.5 on 2025-02-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_complaint_hostelid'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden',
            name='gmail',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
