# Generated by Django 5.1.5 on 2025-02-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_warden_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='category',
            field=models.TextField(default='Physics'),
            preserve_default=False,
        ),
    ]
