# Generated by Django 6.1.1 on 2026-10-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_discussion_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='discussion',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
